version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ev_subsidy
      POSTGRES_USER: ev
      POSTGRES_PASSWORD: evpass
    ports:
      - "5432:5432"
    volumes:
      - ./db/migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ev -d ev_subsidy"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://ev:evpass@db:5432/ev_subsidy
      OFFLINE_MODE: "true"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE: http://api:8000
    ports:
      - "3000:3000"
    depends_on:
      - api

# Optional: a web container can be added later for Next.js
